version: '3.3'
services:
### MySQL Container
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: osd
    build:
      context: .
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      # - ${PWD}/mysql_data/:/var/lib/mysql/
      - ${PWD}/mysql_database_init_files/:/docker-entrypoint-initdb.d/
