version: '3.3'

services:
  tomcat-osd-container:
    image: tomcat:latest
    container_name: tomcat-osd-container
    ports:
      - "8082:8080"
    volumes:
      - /Users/David/Desktop/Spring2023/CS160/OfficeSupplyDepot/OfficeSupplyDepotServlet/target/OfficeSupplyDepot.war:/usr/local/tomcat/webapps/OfficeSupplyDepot.war
    environment:
      - MYSQL_URL=jdbc:mysql://localhost:3306/OfficeSupplyDepot?useSSL=false&useTimezone=true&serverTimezone=America/Los_Angeles
      - MYSQL_USERNAME=david
      - MYSQL_PASSWORD=!Changeme123
      - MYSQL_ROOT_PASSWORD=!Changeme123
