FROM mysql:latest

LABEL maintainer="David Warshawsky <davidawarshawsky@gmail.com>"


ARG MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

WORKDIR /app

EXPOSE $MYSQL_PORT
