version: '3.3'
services:
### MySQL Container
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: osd
    build:
      context: .
      args:
        - MYSQL_ROOT_PASSWORD=!Changeme123
    environment:
      - MYSQL_ROOT_PASSWORD=!Changeme123
    ports:
      - 3306:3306
    volumes:
      # - /Users/David/Desktop/Spring2023/CS160/OfficeSupplyDepot/mysql_data/:/var/lib/mysql/
      - /Users/David/Desktop/Spring2023/CS160/OfficeSupplyDepot/mysql_database_init_files/:/docker-entrypoint-initdb.d/
